{- Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do
not exceed four million, find the sum of the even-valued terms.
-}

fibo :: Int -> Int
fibo 1 = 1
fibo 2 = 2
fibo n = fibo(n-1) + fibo(n-2)

fiboList :: [Int]
fiboList = [ fibo n | n<-[1..]]
--  fibs = 1 : 1 : zipWith (+) fibs (tail fibs)

problem_2 :: Int
problem_2 = sum [ x | x <- takeWhile (<= 4000000) fiboList, even x]
